### ISSUE TITLE
`[GraphQL] Access Denied` error on batch creation in admin console

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#178]
When I click the "Create" button in the new batch dialog, I'm frequently presented with this error (almost(?) always deployed on the production server):
<img width="872" alt="image" src="https://user-images.githubusercontent.com/4304478/199798996-0e43ab93-b8a0-4810-b953-63e740f8a94b.png">
It seems to be related to logging into the admin console, or more specifically, that I was able to access the admin console page without entering the username and password. If I type `window.localStorage.clear()` in the browser console, and refresh, then I am  able to proceed as normal (or, if I use incognito mode). 

It seems that a flag is being set in the localStorage that tells empirica that I don't need to log in again to the admin console, but the authentication hasn't really happened. Could maybe be fixed by either clearing that flag in the localStorage, or persisting the graphql authentication details alongside the flag?

### environment:
- docker build 152
- "@empirica/core": "1.0.0-rc.16",
- deployed on digitalOcean

**Comment by JamesPHoughton** [comment]
Not sure if this is related, but this is showing up for some of my collaborators when they try and access the admin console: 
<img width="630" alt="image" src="https://user-images.githubusercontent.com/4304478/200002797-d8a1ae09-a28a-4783-b13a-ecca04f8b660.png">

**Comment by npaton** [comment]
I think that the last one might be due to scams happening on ondigitalocean.com subdomain: https://www.digitaltrends.com/computing/hackers-using-clever-microsoft-edge-malvertising-scam/. I can see Microsoft using a hammer here. Google doesn't see any problems: https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fdeliberation-9fltg.ondigitalocean.app%2F&hl=en

I guess the solution would be moving to a custom domain.

This comment is about the Microsoft Defender thing. Not the Access Denied, still looking into that one.

**Comment by npaton** [comment]
The admin issue seems to be that a bad token is not cleared from localStorage. A fix is coming in the next release.

**Comment by npaton** [comment]
The Access Denied issue _should_ be fixed in the latest release.

**Comment by JamesPHoughton** [comment]
I'm still seeing this issue when running on the production server. Is there any logging/browser state around this that it would be helpful for me to capture for debugging? There isn't really much going on in the console...


### ENV
ghcr.io/empiricaly/empirica:build-154
"@empirica/core": "1.0.0-rc.23"

**Comment by JamesPHoughton** [comment]
This is still active on Empirica 1.0.0

**Comment by npaton** [comment]
I haven't seem this is a long time, I think it's no longer an issue.
